### ISSUE TITLE
Remove views/pets/create.js.erb

### ISSUE THREAD

**Issue by nathanallen** [petid-project/petid_app#55]

**Comment by cachrisman** [comment]
can i get more of a description of the problem here?  create.js.erb provides functionality for when the user adds a pet from the users#show view to hide the form, clear the form, add the newly added pet to the list of pets, and highlight the newly added pet.

**Comment by cachrisman** [comment]
we realize this is an antipattern and not the best way to accomplish what we are doing, but for now...
